# Generated by Django 5.0 on 2023-12-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=50)),
                ('taskDescription', models.TextField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('categories', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
